"""Developmental acquisition: babble, POS inference, continual learning, wobbly replay.

Naming:
  pos_inference.py              — OOV category inference from grounding + exposure
  bootstrap.py                  — shim → pos_inference
  wobbly.replay_wobbly_episodes — error-driven remedial replay (not POS inference)
"""

from .adaptive import (
    AdaptiveHint,
    AdaptivePlan,
    MisclassificationTarget,
    RemediationResult,
    apply_adaptive_plan,
    build_adaptive_plan,
    build_remedial_sentences,
    collect_misclassifications,
)
from .babble import BabbleReport, register_early_fuzzy_variants, train_babble_stage
from .pos_inference import (
    bootstrap_confidence,
    bootstrap_holdout_categories,
    classify_word_bootstrapped,
    decompose_holdout_classification,
    emergent_fuse_signals,
    grounding_evidence_scores,
    infer_holdout_categories,
    ingest_holdout_sentence_stats,
    is_word_in_lexicon,
    pos_inference_confidence,
    record_exposure_sentence,
    record_wobbly_resolution,
    sentences_from_exposure_log,
    sentences_from_transition_paths,
    signal_confidence,
)
from .continual import (
    StabilityReport,
    StabilitySnapshot,
    capture_stability_snapshot,
    compare_stability,
    replay_corpus_sample,
    stability_gate_after_session,
)
from .wobbly import (
    WobblyEpisode,
    WobblyMemory,
    WobblyProbe,
    bootstrap_from_wobbly_memory,
    format_wobbly_report,
    generate_pos_hypotheses,
    mine_and_bootstrap_from_exposure,
    mine_wobbly_episodes,
    parse_with_wobbly_probes,
    replay_wobbly_episodes,
    resolve_wobbly_hypotheses,
)
from .orchestrator import (
    DEVELOPMENTAL_STAGE_ORDER,
    AcquisitionReport,
    StageReflection,
    acquisition_report_to_dict,
    format_acquisition_report,
    reflect_after_stage,
    run_developmental_acquisition,
)
from .stage_gates import (
    DEFAULT_STAGE_GATE_FLOORS,
    StageGateResult,
    evaluate_stage_gate,
    inter_stage_sleep,
)
from .phonology import (
    EARLY_FUZZY_LEMMAS,
    fuzzy_variants,
    generate_babble_forms,
    generate_babble_utterances,
    normalize_surface_form,
)

__all__ = [
    "DEVELOPMENTAL_STAGE_ORDER",
    "EARLY_FUZZY_LEMMAS",
    "AcquisitionReport",
    "AdaptiveHint",
    "AdaptivePlan",
    "BabbleReport",
    "DEFAULT_STAGE_GATE_FLOORS",
    "MisclassificationTarget",
    "StageGateResult",
    "WobblyEpisode",
    "WobblyMemory",
    "WobblyProbe",
    "RemediationResult",
    "StageReflection",
    "StabilityReport",
    "StabilitySnapshot",
    "acquisition_report_to_dict",
    "apply_adaptive_plan",
    "bootstrap_confidence",
    "bootstrap_holdout_categories",
    "build_adaptive_plan",
    "build_remedial_sentences",
    "capture_stability_snapshot",
    "classify_word_bootstrapped",
    "collect_misclassifications",
    "compare_stability",
    "decompose_holdout_classification",
    "emergent_fuse_signals",
    "evaluate_stage_gate",
    "format_acquisition_report",
    "format_wobbly_report",
    "generate_pos_hypotheses",
    "fuzzy_variants",
    "generate_babble_forms",
    "generate_babble_utterances",
    "grounding_evidence_scores",
    "infer_holdout_categories",
    "ingest_holdout_sentence_stats",
    "inter_stage_sleep",
    "pos_inference_confidence",
    "is_word_in_lexicon",
    "mine_and_bootstrap_from_exposure",
    "mine_wobbly_episodes",
    "normalize_surface_form",
    "parse_with_wobbly_probes",
    "replay_wobbly_episodes",
    "bootstrap_from_wobbly_memory",
    "resolve_wobbly_hypotheses",
    "reflect_after_stage",
    "register_early_fuzzy_variants",
    "record_exposure_sentence",
    "record_wobbly_resolution",
    "replay_corpus_sample",
    "run_developmental_acquisition",
    "sentences_from_exposure_log",
    "sentences_from_transition_paths",
    "signal_confidence",
    "stability_gate_after_session",
    "train_babble_stage",
]
