"""Finite-group word problems: the groups must be the groups they claim.

A generating set that fails to generate produces a PROPER SUBGROUP -- an easier
task, silently reported under the harder group's name. Closure is asserted
against the known order for exactly that reason, and these tests check the
algebra rather than the network, because a wrong group makes every network
number meaningless.
"""

from __future__ import annotations

import unittest

from neural_assemblies.programs.word_problems import (
    GROUPS, true_trajectory, word_problem_fsm,
)

EXPECTED_ORDER = {"Z60": 60, "A4xZ5": 60, "A5": 60, "S5": 120}
EXPECTED_SOLVABLE = {"Z60": True, "A4xZ5": True, "A5": False, "S5": False}


class TestGroups(unittest.TestCase):

    def test_orders_and_solvability(self):
        for name, factory in GROUPS.items():
            g = factory()
            self.assertEqual(g.order, EXPECTED_ORDER[name], name)
            self.assertEqual(g.solvable, EXPECTED_SOLVABLE[name], name)

    def test_three_arms_are_matched_in_order(self):
        """Z60, A4xZ5 and A5 all have order 60, so an arm that degrades on A5
        is degrading on SOLVABILITY and not on the number of states."""
        orders = {n: GROUPS[n]().order for n in ("Z60", "A4xZ5", "A5")}
        self.assertEqual(set(orders.values()), {60}, orders)

    def test_group_axioms_hold(self):
        for name, factory in GROUPS.items():
            g = factory()
            els = g.elements
            for e in els[:12]:
                self.assertEqual(g.compose(e, g.identity), e, name)
                self.assertEqual(g.compose(g.identity, e), e, name)
                self.assertIn(g.compose(e, els[3]), els, name)
            a, b, c = els[1], els[5], els[7]
            self.assertEqual(g.compose(g.compose(a, b), c),
                             g.compose(a, g.compose(b, c)), name)

    def test_non_abelian_groups_really_are(self):
        """A4xZ5 must be non-abelian, or the middle arm is a second Z60.

        Over ALL pairs, not a prefix: elements are ordered by `repr`, and the
        first ten of A4xZ5 happen to commute with each other, so a prefix scan
        reported it abelian.
        """
        for name in ("A4xZ5", "A5", "S5"):
            g = GROUPS[name]()
            self.assertTrue(
                any(g.compose(a, b) != g.compose(b, a)
                    for a in g.elements for b in g.elements),
                f"{name} is abelian")
        z = GROUPS["Z60"]()
        self.assertTrue(all(z.compose(a, b) == z.compose(b, a)
                            for a in z.elements for b in z.elements))


class TestFsmForm(unittest.TestCase):

    def test_transition_table_is_total_and_deterministic(self):
        for name, factory in GROUPS.items():
            g = factory()
            states, symbols, transitions = word_problem_fsm(g)
            self.assertEqual(len(states), g.order, name)
            keys = {(fr, sym) for fr, sym, _ in transitions}
            self.assertEqual(len(keys), len(transitions), f"{name} nondeterministic")
            self.assertEqual(len(transitions), len(states) * len(symbols), name)

    def test_ground_truth_matches_the_table(self):
        """`true_trajectory` and the FSM table must be the same machine --
        otherwise the experiment scores the network against a third thing."""
        for name, factory in GROUPS.items():
            g = factory()
            _states, symbols, transitions = word_problem_fsm(g)
            table = {(fr, sym): to for fr, sym, to in transitions}
            word = [symbols[i % len(symbols)] for i in range(17)]
            expected, current = [], g.label(g.identity)
            for s in word:
                current = table[(current, s)]
                expected.append(current)
            self.assertEqual(true_trajectory(g, word), expected, name)

    def test_a_random_word_visits_most_of_the_group(self):
        """The evaluation word must actually exercise the state space.

        ALTERNATING the two generators does NOT: g0 g1 g0 g1 ... walks the
        CYCLIC subgroup generated by g0.g1, which on A5 is 11 states out of 60
        and periodic by construction. That is an easier task than the group's
        word problem, so the experiment draws its word at RANDOM and this
        pins the reason.
        """
        import random
        g = GROUPS["A5"]()
        _s, symbols, _t = word_problem_fsm(g)
        rng = random.Random(4242)
        traj = true_trajectory(g, [rng.choice(symbols) for _ in range(400)])
        self.assertGreater(len(set(traj)), g.order // 2)

        alternating = true_trajectory(g, [symbols[i % 2] for i in range(400)])
        self.assertLess(len(set(alternating)), g.order // 2)


if __name__ == "__main__":
    unittest.main()
